language: node_js
node_js:
- lts/*
before_install:
- npm install -g grunt-cli
notifications:
  email:
    on_success: change
    on_failure: change
sudo: required
cache:
  directories:
  - node_modules
addons:
  chrome: stable
deploy:
  provider: npm
  email: stdavis@utah.gov
  api_key:
    secure: KXqwxbz5cNpDwCBhdZ8fKlhsewvcP0PyM4NYSJctI7+kzD36zjjeZXJb+c7jaRtqxgK0GgUlpFISEiiCha/zuYpbZGAQkJ6HganuLt0SxOwXn7lzqYAC7IUENNqHLM9A95LuywMLua0WWeqpx+nIbHyJJ/7XQeOwT8/25rKprqohxO52LaEwMjmI/ivT5tCOTLb1ibY7hxddPFTSweh3BsmtRMItiVG0RVBuqtkgor/r6of52mm7w+AGoSky7obUx1y19xSd2JyDF+7x59mgqxQDtA4ac0RmP36DrF9w1bFwkRKnFUqSb3YcHIPA9Jr5oYYtwJOP0TzHRzZNyFGGCBoH6cHWjNTU83N7RC6vo15Di29xeY8Tn3xSh8vSyB0QFKPxgMsE3UdYnIFo/3LBjaVzw80zk3guV17ypPnR1f1GAOws8XKBW5S7AMZuVuBMOPH2FwnZp5FFx/Lskxtbve2q8zgLtzGvHXPEHZQhg7VKkMVKnst1+Z7f54ftPiLtTmI/XRVNT6EJjV+yspNNcxLH01U1BbhfhLD2CWkrC/EZE6pOLj8Wu+2XzEbpttBS90aI0E8GhT5esaEzHBMvd1MNRUf0WARSxOVwKSP3VaionZlxErCNrv4vkkRwIyp5LKTOUmDZUl6Z7ai2iNydrO0ZFXciUgtSTlEpP8NHLjg=
  on:
    tags: true
    repo: agrc-widgets/map-tools
