language: node_js
node_js:
- lts/*
before_install:
- npm install -g grunt-cli
notifications:
  email:
    on_success: change
    on_failure: change
sudo: required
cache:
  directories:
  - node_modules
addons:
  chrome: stable
deploy:
  provider: npm
  email: stdavis@utah.gov
  api_key:
    secure: WidrScStWDTsiL7EHcdhU3fLkmQ66v2VGzF1YAHevcI9utJoW4EaEa4lE3RA3V7Q9xv0/r8eWODyw+zgEnjJvWB+pYxkA0CqWYh0Ffoybsyrh3bo4mYR3gTILttFNie4OaJ7vdR3ePtBP6W/m1M1+Pm+5zTpy40fxOAnN6x89aYkgjlB5CA8z24Em4PRp1UkPchxQz+J6dJsQOMgg2SAxiyIiA1/FZsscArnza6ch1wsbi+X/NvCqOj+drdEubcaTxSKaxg0gBKWU8m36OFHhIilpe2JSpM1kXiAZIsMM/mPEsmSoVeSQii5sJLe6OOUPUDqG9I0gtWFjP0uYEN6EUvxeE3LIRs9rV9TUCI2g7YSSj908wdBjSqnbrpoIHr2OmtFufe5zO9yMLJgg1v2K9kTWC1nKwGbxw5G+5yK0PLAbuMIfcxSrxSf3rTDs8rFLxMro0O2vPeTUjCaWk+Jvsl8CZIYneZ9GzzibkQZibait1A1Pdc/EHO+IYiJgXEPDG23zgiMS9PfxE593P2m1yCWG4NWHxx/YKY+5CXRuFqaOu2ROIk1YPnlTrWXFa3U08ilDF0DiuLOChcPZucXEq/fFhmt61JZspWaQkfyq9g2eEu/q7R8m/yk+Uvf75JkXppZUCFvpQV7Y6CAeynHZw3us32pZKyi7bu/xtJi9hM=
  on:
    tags: true
    repo: agrc-widgets/map-tools
